services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    hostname: flaresolverr
    restart: always
    environment:
      - CAPTCHA_SOLVER=hcaptcha-solver
