services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    volumes:
      - configjellyfin:/config
      - /etc/localtime:/etc/localtime:ro
      - /home/elliot/temp:/cache
      - torrents:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${TRAEFIK_DOMAIN}`)"
      - "traefil.http.services.jellyfin.loadbalancer.server.port=8096"
    ports:
      - 8096:8096

volumes:
  configjellyfin:
    driver: local-persist
    driver_opts:
      mountpoint: /data/config/jellyfin
