version: "3.8"
services:
  adguard:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: always
    volumes:
      - configpihole:/etc/pihole
    environment:
      - TZ:"America/Santo_Domingo"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/tcp
      - 67:67/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
volumes:
    configpihole:
      driver: local-persist
      driver_opts:
          mountpoint: /data/config/pihole
